app:    #这个app随便取,只是个目标名
	g++ test.cpp -I/usr/include/jsoncpp -std=c++11 -lopencv_core -lopencv_imgcodecs -lopencv_videoio  -lcurl -lcrypto -ljsoncpp -o test.exe

.PHONY:clean#伪目标
clean:
	rm test.exe
